/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TratamentosRouteImport } from './routes/tratamentos'
import { Route as AdminPromocoesRouteImport } from './routes/admin.promocoes'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosRoute = TratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/admin/promocoes',
  path: '/admin/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tratamentos': typeof TratamentosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tratamentos': typeof TratamentosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tratamentos': typeof TratamentosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/faq'
    | '/sitemap.xml'
    | '/tratamentos'
    | '/admin/promocoes'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/faq'
    | '/sitemap.xml'
    | '/tratamentos'
    | '/admin/promocoes'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/faq'
    | '/sitemap.xml'
    | '/tratamentos'
    | '/admin/promocoes'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  FaqRoute: typeof FaqRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TratamentosRoute: typeof TratamentosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos': {
      id: '/tratamentos'
      path: '/tratamentos'
      fullPath: '/tratamentos'
      preLoaderRoute: typeof TratamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promocoes': {
      id: '/admin/promocoes'
      path: '/admin/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  FaqRoute: FaqRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TratamentosRoute: TratamentosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
